---
- name: Install python-dev stuff, Nginx, supervisor, uswgi, droopy
  hosts: lancer-server
  remote_user: mtabara
  sudo: yes

  roles:
    - pythondevtools
    - supervisor-uwsgi
    - nginx
    - webapp

