---
# Tasks to install basic python dev modules
# Expects Debian >= 7

- name: install common packages for python app development
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - libmysqlclient-dev
    - libxml2-dev
    - libjpeg62
    - libjpeg62-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - mysql-client
    - python-dev
    - python-setuptools
    - python-imaging
    - python-mysqldb
    - python-psycopg2
    - git-core
    - build-essential

- name: install pip and virtualenv
  easy_install: name={{ item }}
  with_items:
    - pip
    - virtualenv
